apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.selector }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "{{ .Values.selector }}"
  replicas: 1
  selector:
    matchLabels:
      role: {{ .Values.selector }}
  template:
    metadata:
      labels:
        role: {{ .Values.selector }}
    spec:  
      containers:
      - name: {{ .Values.selector }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"    
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 27017  
        command:
          - mongod
        args:    
          - "--replSet"    
          - rs0
          - "--bind_ip_all"

      #   volumeMounts:
      #   - name: mongo-storage
      #     mountPath: /data/db          

      # volumes:
      # - name: mongo-storage
      #   hostPath:
      #     path: /data
      #     type: Directory