apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.selector }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.selector }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    role: {{ .Values.selector }}