FROM golang:1.19.3-alpine AS BuildStage

ARG NAMESPACE_TO_WATCH
ARG OTHER_NAMESPACE_TO_WATCH
ARG KUBECONFIG
WORKDIR /ng

COPY . .

RUN go mod download
RUN go build -o /app main.go

# Deploy Stage
FROM alpine:latest
WORKDIR /
COPY --from=BuildStage /app /app

ENV NAMESPACE_TO_WATCH=${NAMESPACE_TO_WATCH:-default}
ENV OTHER_NAMESPACE_TO_WATCH=${OTHER_NAMESPACE_TO_WATCH:-default}
ENV KUBECONFIG=${KUBECONFIG}

ENTRYPOINT ["/app"]