apiVersion: v1
kind: Namespace
metadata:
  name: app1
---

kind: Service
apiVersion: v1
metadata:
  name: service-mongo
  namespace: app1
spec:
  type: ExternalName
  externalName: mongo.ng-mongo.svc.cluster.local
  ports:
  - port: 27017

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: ng-service-account
  namespace: app1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ng-cluster-role
  namespace: app1
rules:

  - apiGroups: ["", "apps/v1"]
    resources: ["pods", "deployments"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ng-cluster-role-binding
subjects:
- namespace: app1
  kind: ServiceAccount
  name: ng-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ng-cluster-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app1
    do: notmonitor
  name: app1
  namespace: app1
spec:
  replicas: 0
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app1
        do: notmonitor
    spec:
      serviceAccountName: ng-service-account
      containers:
      - image: ng-app1:v1
        imagePullPolicy: Never # So it will use the local image
        name: app1
        resources: {}
status: {}
