apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.common_name }}
    do: {{ .Values.deployment.notmonitor }}
  name: {{ .Values.common_name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.common_name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.common_name }}
        do: notmonitor
    spec:
      serviceAccountName: {{ .Values.common_name }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: NAMESPACE_TO_WATCH
          value: "{{ .Values.common_name }}"
        - name: OTHER_NAMESPACE_TO_WATCH
          value: "{{ .Values.other_namespace_to_watch }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.common_name }}
        resources: 
          {{- toYaml .Values.resources | nindent 10 }}        