apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.common_name }}
  namespace: {{ .Release.Namespace }}
subjects:
- namespace: {{ .Values.common_name }}
  kind: ServiceAccount
  name: {{ .Values.common_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.common_name }}