apiVersion: v1
kind: Namespace
metadata:
  name: ng-mongo

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
  namespace: ng-mongo
provisioner: kubernetes.io/no-provisioner
# provisioner: k8s.io/minikube-hostpath
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-creds
  namespace: ng-mongo
type: Opaque
data:
  mongodb-root-password:  "cm9vdA=="
  mongodb-root-user:  "cm9vdA=="

---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: ng-mongo
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /tmp
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minikube 

---

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: ng-mongo
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: database
  clusterIP: None
  selector:
    role: mongo

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: ng-mongo
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      role: mongo
  template:
    metadata:
      labels:
        role: mongo
    spec:
      containers:
      - name: mongo
        image: mongo             
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
        env:
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: test
          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: test
          # - name: MONGO_INITDB_DATABASE
          #   value: ng-db          
          # - name: MONGO_INITDB_ROOT_USERNAME
          #   value: "test"
            # valueFrom:
            #   secretKeyRef:
            #     name: mongo-creds
            #     key: mongodb-root-user

          # - name: MONGO_INITDB_ROOT_PASSWORD
          #   value: "test"   
            # valueFrom:
            #   secretKeyRef:
            #     name: mongo-creds
            #     key: mongodb-root-password    

          # - name: MONGO_INITDB_DATABASE
          #   value: "ng-db"      

      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          # https://github.com/cvallance/mongo-k8s-sidecar#settings
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongo"
  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 10Gi
      
